/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

    import java.sql.Connection;
    import java.sql.DriverManager;
    import java.sql.PreparedStatement;
    import java.sql.SQLException;
    import javax.swing.JOptionPane;
    import java.sql.ResultSet;

/**
 *
 * @author anderson.peruci
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
    }

    public TelaMenu(String usuario, String cargo) {
        initComponents();
        pnlCadPdt.setVisible(false);
        lblSaudacao.setText("Bem vindo(a)!! " + usuario);
        btnExcluirPdt.setVisible(false);
        if (cargo.equalsIgnoreCase("caixa")) {
            habilitar();
        }
    }

    private void habilitar() {
        itmCadastrarPdt.setEnabled(false);
        itmAlterarPdt.setEnabled(false);
        itmExcluirPdt.setEnabled(false);
        itmRelatorioPdt.setEnabled(true);
        lblMnuFuncionarios.setEnabled(false);
        itmAlterarFcn.setEnabled(false);
        itmExcluirFcn.setEnabled(false);
        itemRelatorioFcn.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblSaudacao = new javax.swing.JLabel();
        pnlCadPdt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblCodigoPdt = new javax.swing.JLabel();
        txtCodigoPdt = new javax.swing.JTextField();
        lblNomePdt = new javax.swing.JLabel();
        txtNomePdt = new javax.swing.JTextField();
        lblCategoriaPdt = new javax.swing.JLabel();
        txtCategoriaPdt = new javax.swing.JTextField();
        lblPrecoPdt = new javax.swing.JLabel();
        txtPrecoPdt = new javax.swing.JTextField();
        btnSalvarPdt = new javax.swing.JButton();
        btnConsultarPdt = new javax.swing.JButton();
        btnAlterarPdt = new javax.swing.JButton();
        btnExcluirPdt = new javax.swing.JButton();
        btnOutrosPdt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        lblMnuProdutos = new javax.swing.JMenu();
        itmCadastrarPdt = new javax.swing.JMenuItem();
        itmAlterarPdt = new javax.swing.JMenuItem();
        itmExcluirPdt = new javax.swing.JMenuItem();
        itmRelatorioPdt = new javax.swing.JMenuItem();
        lblMnuFuncionarios = new javax.swing.JMenu();
        itmCadastrarFcn = new javax.swing.JMenuItem();
        itmAlterarFcn = new javax.swing.JMenuItem();
        itmExcluirFcn = new javax.swing.JMenuItem();
        itemRelatorioFcn = new javax.swing.JMenuItem();
        lblMnuAjuda = new javax.swing.JMenu();
        itmManual = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setTitle("Menu");
        getContentPane().setLayout(null);

        lblSaudacao.setFont(new java.awt.Font("Source Code Pro", 1, 14)); // NOI18N
        lblSaudacao.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblSaudacao);
        lblSaudacao.setBounds(545, 0, 213, 22);

        pnlCadPdt.setBackground(new java.awt.Color(255, 255, 204));
        pnlCadPdt.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Source Serif Pro", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("         Cadastrar Produto");
        pnlCadPdt.add(jLabel2);
        jLabel2.setBounds(290, 40, 200, 30);

        lblCodigoPdt.setFont(new java.awt.Font("Source Code Pro", 1, 13)); // NOI18N
        lblCodigoPdt.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigoPdt.setText("Código:");
        pnlCadPdt.add(lblCodigoPdt);
        lblCodigoPdt.setBounds(140, 110, 120, 30);

        txtCodigoPdt.setBackground(new java.awt.Color(255, 255, 255));
        pnlCadPdt.add(txtCodigoPdt);
        txtCodigoPdt.setBounds(290, 110, 210, 30);

        lblNomePdt.setFont(new java.awt.Font("Source Sans Pro", 1, 13)); // NOI18N
        lblNomePdt.setForeground(new java.awt.Color(0, 0, 0));
        lblNomePdt.setText("Nome:");
        pnlCadPdt.add(lblNomePdt);
        lblNomePdt.setBounds(140, 150, 110, 30);

        txtNomePdt.setBackground(new java.awt.Color(255, 255, 255));
        pnlCadPdt.add(txtNomePdt);
        txtNomePdt.setBounds(290, 150, 210, 30);

        lblCategoriaPdt.setFont(new java.awt.Font("Source Code Pro", 1, 13)); // NOI18N
        lblCategoriaPdt.setForeground(new java.awt.Color(0, 0, 0));
        lblCategoriaPdt.setText("Categoria");
        pnlCadPdt.add(lblCategoriaPdt);
        lblCategoriaPdt.setBounds(140, 190, 110, 30);

        txtCategoriaPdt.setBackground(new java.awt.Color(255, 255, 255));
        txtCategoriaPdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaPdtActionPerformed(evt);
            }
        });
        pnlCadPdt.add(txtCategoriaPdt);
        txtCategoriaPdt.setBounds(290, 190, 210, 30);

        lblPrecoPdt.setFont(new java.awt.Font("Source Code Pro", 1, 13)); // NOI18N
        lblPrecoPdt.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecoPdt.setText("Preço:");
        pnlCadPdt.add(lblPrecoPdt);
        lblPrecoPdt.setBounds(140, 230, 120, 30);

        txtPrecoPdt.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecoPdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoPdtActionPerformed(evt);
            }
        });
        pnlCadPdt.add(txtPrecoPdt);
        txtPrecoPdt.setBounds(290, 230, 210, 30);

        btnSalvarPdt.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvarPdt.setFont(new java.awt.Font("Source Code Pro", 1, 14)); // NOI18N
        btnSalvarPdt.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvarPdt.setText("Salvar");
        btnSalvarPdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPdtActionPerformed(evt);
            }
        });
        pnlCadPdt.add(btnSalvarPdt);
        btnSalvarPdt.setBounds(320, 320, 160, 40);

        btnConsultarPdt.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultarPdt.setFont(new java.awt.Font("Source Code Pro", 1, 13)); // NOI18N
        btnConsultarPdt.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultarPdt.setText("Colsultar");
        btnConsultarPdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPdtActionPerformed(evt);
            }
        });
        pnlCadPdt.add(btnConsultarPdt);
        btnConsultarPdt.setBounds(500, 110, 120, 24);

        btnAlterarPdt.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterarPdt.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        btnAlterarPdt.setForeground(new java.awt.Color(0, 0, 0));
        btnAlterarPdt.setText("Alterar");
        btnAlterarPdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPdtActionPerformed(evt);
            }
        });
        pnlCadPdt.add(btnAlterarPdt);
        btnAlterarPdt.setBounds(480, 320, 150, 40);

        btnExcluirPdt.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluirPdt.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnExcluirPdt.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluirPdt.setText("Excluir");
        btnExcluirPdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPdtActionPerformed(evt);
            }
        });
        pnlCadPdt.add(btnExcluirPdt);
        btnExcluirPdt.setBounds(150, 320, 170, 40);

        btnOutrosPdt.setBackground(new java.awt.Color(255, 255, 255));
        btnOutrosPdt.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnOutrosPdt.setForeground(new java.awt.Color(0, 0, 0));
        btnOutrosPdt.setText("Outros Relatórios");
        btnOutrosPdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutrosPdtActionPerformed(evt);
            }
        });
        pnlCadPdt.add(btnOutrosPdt);
        btnOutrosPdt.setBounds(630, 110, 150, 24);

        getContentPane().add(pnlCadPdt);
        pnlCadPdt.setBounds(0, 0, 800, 550);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\anderson.peruci\\Desktop\\imagenpadaria\\desenho2.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 550);

        lblMnuProdutos.setMnemonic('p');
        lblMnuProdutos.setText("Produtos");

        itmCadastrarPdt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmCadastrarPdt.setText("Cadastrar");
        itmCadastrarPdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarPdtActionPerformed(evt);
            }
        });
        lblMnuProdutos.add(itmCadastrarPdt);

        itmAlterarPdt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmAlterarPdt.setText("Alterar");
        itmAlterarPdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarPdtActionPerformed(evt);
            }
        });
        lblMnuProdutos.add(itmAlterarPdt);

        itmExcluirPdt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmExcluirPdt.setText("Excluir");
        itmExcluirPdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirPdtActionPerformed(evt);
            }
        });
        lblMnuProdutos.add(itmExcluirPdt);

        itmRelatorioPdt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmRelatorioPdt.setText("Relatório");
        itmRelatorioPdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRelatorioPdtActionPerformed(evt);
            }
        });
        lblMnuProdutos.add(itmRelatorioPdt);

        jMenuBar1.add(lblMnuProdutos);

        lblMnuFuncionarios.setMnemonic('f');
        lblMnuFuncionarios.setText("Funcionários");

        itmCadastrarFcn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmCadastrarFcn.setText("Cadastrar");
        itmCadastrarFcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarFcnActionPerformed(evt);
            }
        });
        lblMnuFuncionarios.add(itmCadastrarFcn);

        itmAlterarFcn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmAlterarFcn.setText("Alterar");
        lblMnuFuncionarios.add(itmAlterarFcn);

        itmExcluirFcn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmExcluirFcn.setText("Excluir");
        itmExcluirFcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirFcnActionPerformed(evt);
            }
        });
        lblMnuFuncionarios.add(itmExcluirFcn);

        itemRelatorioFcn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemRelatorioFcn.setText("Relatórios");
        itemRelatorioFcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRelatorioFcnActionPerformed(evt);
            }
        });
        lblMnuFuncionarios.add(itemRelatorioFcn);

        jMenuBar1.add(lblMnuFuncionarios);

        lblMnuAjuda.setMnemonic('a');
        lblMnuAjuda.setText("Ajuda");

        itmManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmManual.setText("Manual");
        lblMnuAjuda.add(itmManual);

        jMenuBar1.add(lblMnuAjuda);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(813, 575));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmRelatorioPdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRelatorioPdtActionPerformed
        btnOutrosPdt.setVisible(true);
        btnAlterarPdt.setVisible(false);
        btnConsultarPdt.setVisible(true);
        btnSalvarPdt.setVisible(false);
        pnlCadPdt.setVisible(true);
        btnExcluirPdt.setVisible(false);
        txtCodigoPdt.setText("");
        txtNomePdt.setText("");
        txtCategoriaPdt.setText("");
        txtPrecoPdt.setText("");
    }//GEN-LAST:event_itmRelatorioPdtActionPerformed

    private void itmExcluirPdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirPdtActionPerformed
        btnOutrosPdt.setVisible(false);
        btnAlterarPdt.setVisible(false); 
        btnConsultarPdt.setVisible(true);
        btnSalvarPdt.setVisible(false);
        pnlCadPdt.setVisible(true);
        btnExcluirPdt.setVisible(false);
        txtCodigoPdt.setText("");
        txtNomePdt.setText("");
        txtCategoriaPdt.setText("");
        txtPrecoPdt.setText("");
    }//GEN-LAST:event_itmExcluirPdtActionPerformed

    private void itmExcluirFcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirFcnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmExcluirFcnActionPerformed

    private void itmCadastrarFcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarFcnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmCadastrarFcnActionPerformed

    private void itemRelatorioFcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRelatorioFcnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemRelatorioFcnActionPerformed

    private void txtCategoriaPdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaPdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaPdtActionPerformed

    private void txtPrecoPdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoPdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoPdtActionPerformed

    private void btnSalvarPdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPdtActionPerformed
        try {
            Connection conexao;
            PreparedStatement st;
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancopadaria", "root", "Familia1");
            st = conexao.prepareStatement("INSERT INTO cadastarproduto VALUES(?, ?, ?, ?)");
            st.setString(1, txtCodigoPdt.getText());
            st.setString(2, txtNomePdt.getText());
            st.setString(3, txtCategoriaPdt.getText());
            st.setDouble(4, Double.parseDouble(txtPrecoPdt.getText()));
            st.executeUpdate();//executa o Insert acima
            JOptionPane.showMessageDialog(btnSalvarPdt, "Produto salvo com sucesso!!");
            txtCodigoPdt.setText("");
            txtNomePdt.setText("");
            txtCategoriaPdt.setText("");
            txtPrecoPdt.setText("");
            txtCodigoPdt.requestFocus();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(btnSalvarPdt, "Erro" + ex.getMessage() + "\n Entre em contato com o programador");
        } catch (SQLException ex) {
            if (ex.getErrorCode() == 1062) {
                JOptionPane.showMessageDialog(btnSalvarPdt, "Este código de produto ja foi cadastrado");
            } else {
                JOptionPane.showMessageDialog(btnSalvarPdt, "Erro Numero" + ex.getErrorCode() + "Mostre esse numero de erro para o Programdor");
            }

        }
    }//GEN-LAST:event_btnSalvarPdtActionPerformed

    private void itmCadastrarPdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarPdtActionPerformed
        btnOutrosPdt.setVisible(false);
        btnAlterarPdt.setVisible(false);
        btnExcluirPdt.setVisible(false);
        pnlCadPdt.setVisible(true);
        btnSalvarPdt.setVisible(true);
        btnConsultarPdt.setVisible(false);
        btnOutrosPdt.setVisible(false);
        txtCategoriaPdt.setText("");
        txtNomePdt.setText("");
        txtPrecoPdt.setText("");
        txtCodigoPdt.setText("");
        

    }//GEN-LAST:event_itmCadastrarPdtActionPerformed

    private void btnConsultarPdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPdtActionPerformed

        try {
            Connection conexao;
            PreparedStatement st;
            ResultSet resultado;
            //conexao com o banco de dados
            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancopadaria", "root", "Familia1");
            //busca de dados no banco
            st = conexao.prepareStatement("SELECT * FROM cadastarproduto WHERE codigo=?");
            st.setString(1, txtCodigoPdt.getText());
            resultado = (ResultSet) st.executeQuery();//Executa o SELECT a cima;
            if (resultado.next()) {// verifica se ele encontrou o usuario
                txtNomePdt.setText(resultado.getString("Nome"));
                txtCategoriaPdt.setText(resultado.getString("Marca"));
                txtPrecoPdt.setText(resultado.getString("Preco"));
                txtCodigoPdt.requestFocus();
                btnExcluirPdt.setVisible(true);
                btnAlterarPdt.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Código digitado nao cadastrado!");
                txtCodigoPdt.requestFocus();
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(btnConsultarPdt, "Você não tem o driver na biblioteca");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(btnConsultarPdt, "Algum parâmetro do BD está incorreto - ERR: " + ex);
        }

    }//GEN-LAST:event_btnConsultarPdtActionPerformed

    private void itmAlterarPdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarPdtActionPerformed
        btnOutrosPdt.setVisible(false);
        btnAlterarPdt.setVisible(false);
        btnExcluirPdt.setVisible(false);
        pnlCadPdt.setVisible(true);
        btnSalvarPdt.setVisible(false);
        btnConsultarPdt.setVisible(true);
        txtCategoriaPdt.setText("");
        txtNomePdt.setText("");
        txtPrecoPdt.setText("");
        txtCodigoPdt.setText("");
    }//GEN-LAST:event_itmAlterarPdtActionPerformed

    private void btnExcluirPdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPdtActionPerformed
        try {
            Connection conexao;
            PreparedStatement st;
            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancopadaria", "root", "Familia1");
            st = conexao.prepareStatement("DELETE FROM cadastarproduto WHERE codigo=?");
            st.setString(1, txtCodigoPdt.getText());
            int res=st.executeUpdate();
            if (res==1) {
                JOptionPane.showMessageDialog(null, "produto exluido com sucesso");
                txtCategoriaPdt.setText("");
                txtNomePdt.setText("");
                txtPrecoPdt.setText("");
                txtCodigoPdt.setText("");
                txtCodigoPdt.requestFocus();
                btnExcluirPdt.setVisible(false);
                btnAlterarPdt.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possivel excluir produto");
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(btnConsultarPdt, "Você não tem o driver na biblioteca");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(btnConsultarPdt, "Algum parâmetro do BD está incorreto - ERR: " + ex);
        }
    }//GEN-LAST:event_btnExcluirPdtActionPerformed

    private void btnAlterarPdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPdtActionPerformed
           try {
            Connection conexao;
            PreparedStatement st;
            Class.forName("com.mysql.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancopadaria", "root", "Familia1");
            st = conexao.prepareStatement("UPDATE cadastarproduto SET nome = ?, marca = ?, preco = ?  WHERE codigo=?");
            st.setString(1, txtNomePdt.getText());
            st.setString(2, txtCategoriaPdt.getText());
            st.setString(3, txtPrecoPdt.getText());
            st.setString(4, txtCodigoPdt.getText());
            st.executeUpdate(); 
            JOptionPane.showMessageDialog(null, "Produto alterado com Sucesso");
            txtCategoriaPdt.setText("");
            txtNomePdt.setText("");
            txtPrecoPdt.setText("");
            txtCodigoPdt.setText("");
            txtCodigoPdt.requestFocus();
            btnExcluirPdt.setVisible(false);
            btnAlterarPdt.setVisible(false);
            

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(btnConsultarPdt, "Você não tem o driver na biblioteca");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(btnConsultarPdt, "Algum parâmetro do BD está incorreto - ERR: " + ex);
        }
    }//GEN-LAST:event_btnAlterarPdtActionPerformed

    private void btnOutrosPdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutrosPdtActionPerformed
      TelaRelatórios tela;
      tela = new TelaRelatórios();
      tela.setVisible(true);
      
    }//GEN-LAST:event_btnOutrosPdtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarPdt;
    private javax.swing.JButton btnConsultarPdt;
    private javax.swing.JButton btnExcluirPdt;
    private javax.swing.JButton btnOutrosPdt;
    private javax.swing.JButton btnSalvarPdt;
    private javax.swing.JMenuItem itemRelatorioFcn;
    private javax.swing.JMenuItem itmAlterarFcn;
    private javax.swing.JMenuItem itmAlterarPdt;
    private javax.swing.JMenuItem itmCadastrarFcn;
    private javax.swing.JMenuItem itmCadastrarPdt;
    private javax.swing.JMenuItem itmExcluirFcn;
    private javax.swing.JMenuItem itmExcluirPdt;
    private javax.swing.JMenuItem itmManual;
    private javax.swing.JMenuItem itmRelatorioPdt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblCategoriaPdt;
    private javax.swing.JLabel lblCodigoPdt;
    private javax.swing.JMenu lblMnuAjuda;
    private javax.swing.JMenu lblMnuFuncionarios;
    private javax.swing.JMenu lblMnuProdutos;
    private javax.swing.JLabel lblNomePdt;
    private javax.swing.JLabel lblPrecoPdt;
    private javax.swing.JLabel lblSaudacao;
    private javax.swing.JPanel pnlCadPdt;
    private javax.swing.JTextField txtCategoriaPdt;
    private javax.swing.JTextField txtCodigoPdt;
    private javax.swing.JTextField txtNomePdt;
    private javax.swing.JTextField txtPrecoPdt;
    // End of variables declaration//GEN-END:variables
}
